//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4SC1WCFClient.BarangService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarangInfo", Namespace="http://schemas.datacontract.org/2004/07/_4SC1WCFServer")]
    [System.SerializableAttribute()]
    public partial class BarangInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HargaBarangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDBarangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaBarangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StokBarangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HargaBarang {
            get {
                return this.HargaBarangField;
            }
            set {
                if ((this.HargaBarangField.Equals(value) != true)) {
                    this.HargaBarangField = value;
                    this.RaisePropertyChanged("HargaBarang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDBarang {
            get {
                return this.IDBarangField;
            }
            set {
                if ((object.ReferenceEquals(this.IDBarangField, value) != true)) {
                    this.IDBarangField = value;
                    this.RaisePropertyChanged("IDBarang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaBarang {
            get {
                return this.NamaBarangField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaBarangField, value) != true)) {
                    this.NamaBarangField = value;
                    this.RaisePropertyChanged("NamaBarang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StokBarang {
            get {
                return this.StokBarangField;
            }
            set {
                if ((this.StokBarangField.Equals(value) != true)) {
                    this.StokBarangField = value;
                    this.RaisePropertyChanged("StokBarang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BarangService.IBarang")]
    public interface IBarang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarang/getAllBarang", ReplyAction="http://tempuri.org/IBarang/getAllBarangResponse")]
        _4SC1WCFClient.BarangService.BarangInfo[] getAllBarang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarang/insertBarang", ReplyAction="http://tempuri.org/IBarang/insertBarangResponse")]
        string insertBarang(_4SC1WCFClient.BarangService.BarangInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarang/getBarangByID", ReplyAction="http://tempuri.org/IBarang/getBarangByIDResponse")]
        _4SC1WCFClient.BarangService.BarangInfo[] getBarangByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarang/deleteBarang", ReplyAction="http://tempuri.org/IBarang/deleteBarangResponse")]
        string deleteBarang(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarangChannel : _4SC1WCFClient.BarangService.IBarang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarangClient : System.ServiceModel.ClientBase<_4SC1WCFClient.BarangService.IBarang>, _4SC1WCFClient.BarangService.IBarang {
        
        public BarangClient() {
        }
        
        public BarangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _4SC1WCFClient.BarangService.BarangInfo[] getAllBarang() {
            return base.Channel.getAllBarang();
        }
        
        public string insertBarang(_4SC1WCFClient.BarangService.BarangInfo data) {
            return base.Channel.insertBarang(data);
        }
        
        public _4SC1WCFClient.BarangService.BarangInfo[] getBarangByID(string id) {
            return base.Channel.getBarangByID(id);
        }
        
        public string deleteBarang(string id) {
            return base.Channel.deleteBarang(id);
        }
    }
}
