//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4SC1PraktikumClient.PegawaiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PegawaiInfo", Namespace="http://schemas.datacontract.org/2004/07/_4SC1PraktikumService")]
    [System.SerializableAttribute()]
    public partial class PegawaiInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPegawaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPegawaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatPegawaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jeniskelaminPegawaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teleponPegawaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPegawai {
            get {
                return this.IDPegawaiField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPegawaiField, value) != true)) {
                    this.IDPegawaiField = value;
                    this.RaisePropertyChanged("IDPegawai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPegawai {
            get {
                return this.NamaPegawaiField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPegawaiField, value) != true)) {
                    this.NamaPegawaiField = value;
                    this.RaisePropertyChanged("NamaPegawai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamatPegawai {
            get {
                return this.alamatPegawaiField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatPegawaiField, value) != true)) {
                    this.alamatPegawaiField = value;
                    this.RaisePropertyChanged("alamatPegawai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jeniskelaminPegawai {
            get {
                return this.jeniskelaminPegawaiField;
            }
            set {
                if ((object.ReferenceEquals(this.jeniskelaminPegawaiField, value) != true)) {
                    this.jeniskelaminPegawaiField = value;
                    this.RaisePropertyChanged("jeniskelaminPegawai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string teleponPegawai {
            get {
                return this.teleponPegawaiField;
            }
            set {
                if ((object.ReferenceEquals(this.teleponPegawaiField, value) != true)) {
                    this.teleponPegawaiField = value;
                    this.RaisePropertyChanged("teleponPegawai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PegawaiService.IPegawai")]
    public interface IPegawai {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/getPegawaiInfo", ReplyAction="http://tempuri.org/IPegawai/getPegawaiInfoResponse")]
        _4SC1PraktikumClient.PegawaiService.PegawaiInfo[] getPegawaiInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/getPegawaiID", ReplyAction="http://tempuri.org/IPegawai/getPegawaiIDResponse")]
        _4SC1PraktikumClient.PegawaiService.PegawaiInfo[] getPegawaiID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/getPegawaiLastID", ReplyAction="http://tempuri.org/IPegawai/getPegawaiLastIDResponse")]
        string getPegawaiLastID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/insertPegawai", ReplyAction="http://tempuri.org/IPegawai/insertPegawaiResponse")]
        string insertPegawai(_4SC1PraktikumClient.PegawaiService.PegawaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/updatePegawai", ReplyAction="http://tempuri.org/IPegawai/updatePegawaiResponse")]
        string updatePegawai(_4SC1PraktikumClient.PegawaiService.PegawaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPegawai/deletePegawai", ReplyAction="http://tempuri.org/IPegawai/deletePegawaiResponse")]
        string deletePegawai(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPegawaiChannel : _4SC1PraktikumClient.PegawaiService.IPegawai, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PegawaiClient : System.ServiceModel.ClientBase<_4SC1PraktikumClient.PegawaiService.IPegawai>, _4SC1PraktikumClient.PegawaiService.IPegawai {
        
        public PegawaiClient() {
        }
        
        public PegawaiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PegawaiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PegawaiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PegawaiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _4SC1PraktikumClient.PegawaiService.PegawaiInfo[] getPegawaiInfo() {
            return base.Channel.getPegawaiInfo();
        }
        
        public _4SC1PraktikumClient.PegawaiService.PegawaiInfo[] getPegawaiID() {
            return base.Channel.getPegawaiID();
        }
        
        public string getPegawaiLastID() {
            return base.Channel.getPegawaiLastID();
        }
        
        public string insertPegawai(_4SC1PraktikumClient.PegawaiService.PegawaiInfo data) {
            return base.Channel.insertPegawai(data);
        }
        
        public string updatePegawai(_4SC1PraktikumClient.PegawaiService.PegawaiInfo data) {
            return base.Channel.updatePegawai(data);
        }
        
        public string deletePegawai(string id) {
            return base.Channel.deletePegawai(id);
        }
    }
}
